version: "3"
services:
  app:
    build: .
    image: nodejs-postgresql
    ports:
      - 3000:3000
    environment:
      - POOL_SIZE_MAX=50
    depends_on:
      - postgres
  postgres:
    image: postgres
    restart: always
    ports:
    - 5432:5432
    environment:
      POSTGRES_DB: northwind
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
    - ./postgresql_data:/var/lib/postgresql/data
    - ./northwind.sql:/docker-entrypoint-initdb.d/northwind.sql    
